version: '3.7'

services:
  # issuer:
  #   image: issuer-uidai
  #   container_name: issuer
  #   build:
  #     context: ./issuer/
  #   env_file: ./issuer/.env
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - node_modules:/app/node_modules

  # verifier:
  #   image: verifier-telcom
  #   container_name: verifier
  #   build:
  #     context: ./verifier
  #   env_file: ./verifier/.env
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - node_modulesV:/app/node_modules

  # holder:
  #   image: holder-telcom-demo
  #   container_name: holder
  #   build:
  #     context: ./holder
  #   env_file: ./holder/.env
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - node_modulesH:/app/node_modules

  issuer-agent:
    image: custom-agent
    build:
      context: ./agent
    env_file: ./agent/.env
    restart: always
    # environment:
      # - AGENT_ENV=PUBLIC
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/node_modules
  
  holder-agent:
    image: custom-agent
    build:
      context: ./agent
    env_file: ./agent/.env
    environment:
      - AGENT_ENV=LOCAL
      - AGENT_TYPE=holder
      - AGENT_NAME=HOLDER_
    ports:
      - 4000:3000
    volumes:
      - node_modules:/app/node_modules
  
  verifier-agent:
    image: custom-agent
    build:
      context: ./agent
    env_file: ./agent/.env
    environment:
      - AGENT_ENV=LOCAL
      - AGENT_TYPE=verifier
      - AGENT_NAME=VERIFIER_
    ports:
      - 5000:3000
    volumes:
      - node_modules:/app/node_modules

volumes:
  node_modules:
  # node_modulesV:
  # node_modulesH:
